# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: Chocolatey| Clean cache
  ansible.windows.win_file:
    path: '{{ item }}'
    state: absent
  loop:
    - '%UserProfile%\AppData\Local\Temp\chocolatey\'
    - '%UserProfile%\AppData\Local\Temp\nuget\'
    - '%UserProfile%\AppData\Local\NuGet\Cache\'
