# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
# - name: Packages | Emacs
#   chocolatey.chocolatey.win_chocolatey:
#     name: emacs64
#     state: present

- name: Packages | VSCode
  chocolatey.chocolatey.win_chocolatey:
    name: vscode
    state: present

- name: Packages | Neovim
  chocolatey.chocolatey.win_chocolatey:
    name: neovim
    state: present
