# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: Packages | Docker and co
  chocolatey.chocolatey.win_chocolatey:
    chocolatey.chocolatey.win_chocolatey:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - docker-desktop

- name: System | User is in docker group
  ansible.windows.win_group_membership:
    members:
      - "{{ username }}"
    name: "docker-users"

- name: Hyper-V | Install
  ansible.windows.win_feature:
    name: Hyper-V
    include_management_tools: true
  register: hyper_v

- name: System | Reboot
  when: hyper_v.reboot_required
  ansible.windows.win_reboot:
