# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
namespace: divona
name: windows
version: 0.1.0
readme: README.md
authors:
  - Nicolas Lamirault <nicolas.lamirault@gmail.com>
description: your collection description
license:
  - Apache-2.0
license_file: LICENSE
tags:
  - windows
  - workstation
dependencies: {}
repository: http://github.com/divona-roles/ansible-collection-windows
documentation: http://github.com/divona-roles/ansible-collection-windows
homepage: http://github.com/divona-roles/ansible-collection-windows
issues: http://github.com/divona-roles/ansible-collection-windows/issues
build_ignore: []
