# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
collections:
  - name: community.general
    version: 12.3.0
  - name: ansible.windows
    version: 3.3.0
  - name: chocolatey.chocolatey
    version: 1.5.3
  - name: community.windows
    version: 3.3.0

roles: []
