# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Packages | Desktop applications
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ueli

- name: Packages | Web applications
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - googlechrome
      - tor-browser

- name: Packages | Graphics applications
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gimp
      - flameshot

- name: Packages | Video applications
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - vlc

- name: Packages | Music applications
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - spotify

- name: Packages | Communications applications
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - slack

- name: Packages | Security tools
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - keepassxc
      - wireshark
      - 1password
      - tailscale
