# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: Packages | Window manager
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - komorebi
      - glazewm

- name: Packages | Desktop applications
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ueli

- name: Packages | Web applications
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - googlechrome
      - tor-browser

- name: Packages | Graphics applications
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gimp
      - flameshot

- name: Packages | Video applications
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - vlc

- name: Packages | Music applications
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - spotify

- name: Packages | Communications applications
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - slack

- name: Packages | Security tools
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - keepassxc
      - wireshark
      - 1password
      - tailscale
