# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
# defaults file for base

######################################################
# Chocolatey


######################################################
# General

install_windows_updates: true
windows_updates_reboot: true
update_categories:
  # * - installs all updates
  # - "*"
  - Critical Updates
  # - Definition Updates
  # - Developer Kits
  # - Feature Packs
  - Security Updates
  # - Service Packs
  # - Tools
  - Update Rollups
  # - Updates
  # - Upgrades

install_windows_features: false
windows_features:
  Microsoft-Hyper-V: true

install_wsl2: true
# wsl2_distribution: wsl-archlinux
# wsl2_distribution: wsl-debiangnulinux
wsl2_distribution: wsl-ubuntu-2004

user_dirs:
  - Applications
  - Projects
  - Work

xdg_dirs:
  - Documents
  - Downloads
  - Music
  - Pictures
  - Public
  - Templates
  - Videos
