# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: Include OS-specific tasks
  when: ansible_distribution == 'Windows'
  block:
    - name: WM | Core
      ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
