# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: Packages | Windows Manager
  community.windows.win_scoop:
    name: "{{ item }}"
    state: present
  loop:
    - komorebi
    - komokana

- name: Packages | Windows Manager addons
  community.windows.win_scoop:
    name: "{{ item }}"
    state: present
  loop:
    - nerdfont-hack

# OR ?
# https://github.com/LGUG2Z/komorebi/issues/157
# chocolatey.chocolatey.win_chocolatey:
