# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: Packages | Install shell tools
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - fzf

- name: Packages | Install terminal emulators
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - microsoft-windows-terminal
      - cmder

- name: Packages | Install commons tools
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - git
      - cygwin
      - windirstat
