# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

---
- name: System | Ensure Automatic Install of Suggested Apps disabled.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
    name: SilentInstalledAppsEnabled
    data: 0
    type: dword

- name: System | Ensure App Suggestions in Start menu disabled.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
    name: SystemPaneSuggestionsEnabled
    data: 0
    type: dword

- name: System | Ensure popup "tips" about Windows disabled.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
    name: SoftLandingEnabled
    data: 0
    type: dword

- name: System | Ensure 'Windows Welcome Experience' disabled.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
    name: "{{ item }}"
    data: 0
    type: dword
  loop:
    - SubscribedContent-310093Enabled
    - SubscribedContent-338388Enabled
    - SubscribedContent-338389Enabled
    - SubscribedContent-88000326Enabled
