# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: System | Set preferred languages
  ansible.windows.win_user_languages:
    languages:
      - en-US
      - fr-FR

- name: System | Set timezone
  community.windows.win_timezone:
    timezone: GMT Standard Time
