# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: Include OS-specific tasks
  when: ansible_distribution == 'Windows'
  become: true
  become_user: root
  block:
    - name: Base | Defaults
      ansible.builtin.include_tasks: "defaults.yml"
    - name: Base | Taskbar
      ansible.builtin.include_tasks: "taskbar.yml"
    - name: Base | System
      ansible.builtin.include_tasks: "system.yml"
    - name: Base | Locales
      ansible.builtin.include_tasks: "locales.yml"
    - name: Base | Applications
      ansible.builtin.include_tasks: "apps.yml"
